### ISSUE TITLE
죄송하지만 이런기능도 만들어주실수 있으신가요??

### ISSUE THREAD

**Issue by LeePC** [stypr/bnet_capture#1]
안녕하세요 
다름이 아니라 2개월째 어떤 특정유저가 계속 패드립을 날려대서 머리가 너무아픈 1인입니다

아이피 차단기능도 만들어주시면 안될까요??
패드립유저때문에 골치가 너무 아파서 말이죠.....

**Comment by stypr** [comment]
죄송합니다

특정 아이피 들어오면 차단하도록 IPC처리하거나 뭔가 하면 될거 같은데 

제가 더이상 스타크래프트를 하는 것도 아니고, 뭔가 누군가에게 이걸 쓰라고 만든건 아니어서요.

언젠가 정말 여유가 생기면 한번 추가해보겠습니다.
